version: 2

models:  
  - name: andhra_pradesh_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: assam_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: chattisgarh_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: delhi_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: gujarat_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: himachal_pradesh_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: karnataka_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: maharashtra_pmu.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: delhi_vocational_students_exit_survey.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: field_visit_form_lend_a_hand_india.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: pmu_monthly_report.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: gujarat.sql
    description: "Normalized data of Gujarat" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: jharkhand.sql
    description: "Normalized data of Jharkhand" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null