version: 2

models:  
  - name: andhra_pradesh_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: assam_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: chattisgarh_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: delhi_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: gujarat_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: himachal_pradesh_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: karnataka_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: maharashtra_pmu
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: delhi_vocational_students_exit_survey
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: field_visit_form_lend_a_hand_india
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: pmu_monthly_report
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: gujarat_pathways_internship
    description: "Normalized data of Gujarat" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null
  - name: jharkhand_pathways_internship
    description: "Normalized data of Jharkhand" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null