version: 2

models:  
  - name: normalized.sql
    description: "Normalized data of PMU monthly report" 
    +schema: intermediate
    columns: 
       - name: _airbyte_ab_id
         description: "The primary key for this table"
         tests:
           - unique
           - not_null

  