version: 2

sources:
  - name: source_lahi
    schema: staging
    tables:
      - name: delhi_database
        identifier: _airbyte_raw_delhi_pmu_database_22_23_
        description: delhi google sheet
      - name: maharashtra_database
        identifier: _airbyte_raw_state_pmu_database_22_23_
        description: maharashtra google sheet
      - name: gujarat_database
        identifier: _airbyte_raw_gj_pmu_database_22_23
        description: gujarat google sheet
      - name: karnataka_database
        identifier: _airbyte_raw_ka_pmu_database_22_23_
        description: karnataka google sheet
      - name: himachal_pradesh_database
        identifier: _airbyte_raw_hp_pmu_database_22_23_
        description: himachal pradesh google sheet
      - name: assam_database
        identifier: _airbyte_raw_assam_pmu_database_22_23
        description: assam_google sheet
      - name: chattisgarh_database
        identifier: _airbyte_raw_cg_pmu_database_22_23
        description: chattisgarh google sheet
      - name: andhra_pradesh_database
        identifier: _airbyte_raw_andhra_pmu_database_22_23_
        description: andhra pradesh google sheet
      - name: pmu_monthly_report_database
        identifier: _airbyte_raw_pmu_monthly_report
        description: pmu monthly report
      - name: ladakh_database
        identifier: _airbyte_raw_ladakh_pmu_database_22_23_
        description: ladakh database
      - name: nagaland_database
        identifier: _airbyte_raw_ng_pmu_database_22_23
        description: nagaland database
      - name: odisha_database
        identifier: _airbyte_raw_od_pmu_database_22_23_
        description: odisha database
      - name: tamil_nadu_database
        identifier: _airbyte_raw_tn_pmu_database_22_23
        description: tamil nadu database
      - name: telangana_database
        identifier: _airbyte_raw_tl_pmu_database_22_23
        description: telangana database
      - name: pmu_field_visit_database
        identifier: _airbyte_raw_field_visit_form_lend_a_hand_india
        description: pmu field visit
      - name: employee_data_database
        identifier: _airbyte_raw_employee_database
      - name: eligible_school_data
        identifier: _airbyte_raw_eligible_school_database
        description: employee data new
      - name: delhi_pathways_internship
        identifier: _airbyte_raw_delhi
        description: employee data new
      - name: gujarat_pathways_internship
        identifier: _airbyte_raw_gujarat
        description: employee data new
      - name: jharkhand_pathways_internship
        identifier: _airbyte_raw_jharkhand
        description: employee data new
      - name: maharashtra_pathways_internship
        identifier: _airbyte_raw_maharashta
        description: employee data new
      - name: andhra_pradesh_23_24_database
        identifier: _airbyte_raw_andhra_pmu_database_23_24
        description: employee data new
      - name: assam_23_24_database
        identifier: _airbyte_raw_assam_pmu_database_23_24
        description: employee data new
      - name: chattisgarh_23_24_database
        identifier: _airbyte_raw_cg_pmu_database_23_24
        description: employee data new
      - name: delhi_23_24_database
        identifier: _airbyte_raw_delhi_pmu_database_23_24
        description: employee data new
      - name: gujarat_23_24_database
        identifier: _airbyte_raw_gujarat_pmu_database_23_24
        description: employee data new
      - name: himachal_pradesh_23_24_database
        identifier: _airbyte_raw_himachal_pradesh_pmu_database_23_24
        description: employee data new
      - name: jharkhand_23_24_database
        identifier: _airbyte_raw_jharkhand_pmu_database_23_24
        description: employee data new
      - name: karnataka_23_24_database
        identifier: _airbyte_raw_karnataka_state_db_23_24
        description: employee data new
      - name: ladakh_23_24_database
        identifier: _airbyte_raw_ladakh_state_db_23_24
        description: employee data new
      - name: maharashtra_23_24_database
        identifier: _airbyte_raw_mh_pmu_database_23_24
        description: employee data new
      - name: nagaland_23_24_database
        identifier: _airbyte_raw_nagaland_state_db_23_24
        description: employee data new
      - name: odisha_23_24_database
        identifier: _airbyte_raw_odisha_state_db_23_24
        description: employee data new
      - name: punjab_23_24_database
        identifier: _airbyte_raw_pb_pmu_database_23_24
        description: employee data new
      - name: rajasthan_23_24_database
        identifier: _airbyte_raw_rj_state_db_23_24
        description: employee data new
      - name: telangana_23_24_database
        identifier: _airbyte_raw_tl_state_db_23_24
        description: employee data new
      - name: tamil_nadu_23_24_database
        identifier: _airbyte_raw_tn_state_db_23_24
        description: employee data new
      - name: uttarakhand_23_24_database
        identifier: _airbyte_raw_uk_state_db_23_24
        description: employee data new
