version: 2

sources:
  - name: source_lahi
    schema: staging
    tables:
      - name: delhi_database
        identifier: _airbyte_raw_delhi_pmu_database_22_23_
        description: delhi google sheet
      - name: maharashtra_database
        identifier: _airbyte_raw_state_pmu_database_22_23_
        description: maharashtra google sheet
      - name: gujarat_database
        identifier: _airbyte_raw_gj_pmu_database_22_23
        description: gujarat google sheet
      - name: karnataka_database
        identifier: _airbyte_raw_ka_pmu_database_22_23_
        description: karnataka google sheet
      - name: himachal_pradesh_database
        identifier: _airbyte_raw_hp_pmu_database_22_23_
        description: himachal pradesh google sheet
      - name: assam_database
        identifier: _airbyte_raw_assam_pmu_database_22_23
        description: assam_google sheet
      - name: chattisgarh_database
        identifier: _airbyte_raw_cg_pmu_database_22_23
        description: chattisgarh google sheet
      - name: andhra_pradesh_database
        identifier: _airbyte_raw_andhra_pmu_database_22_23_
        description: andhra pradesh google sheet
      - name: pmu_monthly_report_database
        identifier: _airbyte_raw_pmu_monthly_report
        description: pmu monthly report
      - name: ladakh_database
        identifier: _airbyte_raw_ladakh_pmu_database_22_23_
        description: ladakh database
      - name: nagaland_database
        identifier: _airbyte_raw_ng_pmu_database_22_23
        description: nagaland database
      - name: odisha_database
        identifier: _airbyte_raw_od_pmu_database_22_23_
        description: odisha database
      - name: tamil_nadu_database
        identifier: _airbyte_raw_tn_pmu_database_22_23
        description: tamil nadu database
      - name: telangana_database
        identifier: _airbyte_raw_tl_pmu_database_22_23
        description: telangana database
      - name: pmu_field_visit_database
        identifier: _airbyte_raw_field_visit_form_lend_a_hand_india
        description: pmu field visit
      - name: employee_data_database
        identifier: _airbyte_raw_employee_database
        description: employee data new
      - name: delhi_pathways_internship
        identifier: _airbyte_raw_delhi
        description: employee data new
      - name: gujarat_pathways_internship
        identifier: _airbyte_raw_gujarat
        description: employee data new
      - name: jharkhand_pathways_internship
        identifier: _airbyte_raw_jharkhand
        description: employee data new
      - name: maharashtra_pathways_internship
        identifier: _airbyte_raw_maharashta
        description: employee data new
      - name: academic_years
        identifier: _airbyte_raw_academicyears
        description: employee data new
      - name: blocks
        identifier: _airbyte_raw_blocks
        description: employee data new
      - name: countries
        identifier: _airbyte_raw_countries
        description: employee data new
      - name: districts
        identifier: _airbyte_raw_districts
        description: employee data new
      - name: division_districts
        identifier: _airbyte_raw_divisiondistricts
        description: employee data new
      - name: divisions
        identifier: _airbyte_raw_divisions
        description: employee data new
      - name: hm_issue_reporting
        identifier: _airbyte_raw_hmissuereporting
        description: employee data new
      - name: hm_schools_map
        identifier: _airbyte_raw_hmschoolsmap
        description: employee data new
      - name: job_roles
        identifier: _airbyte_raw_jobroles
        description: employee data new
      - name: roles
        identifier: _airbyte_raw_roles
        description: employee data new
      - name: school_categories
        identifier: _airbyte_raw_schoolcategories
        description: employee data new
      - name: school_classes
        identifier: _airbyte_raw_schoolclasses
        description: employee data new
      - name: schools
        identifier: _airbyte_raw_schools
        description: employee data new
      - name: schools_by_vtp_sector_info
        identifier: _airbyte_raw_schoolsbyvtpsectorinfo
        description: employee data new
      - name: school_ve_incharges
        identifier: _airbyte_raw_schoolveincharges
        description: employee data new
      - name: school_vtp_sectors
        identifier: _airbyte_raw_schoolvtpsectors
        description: employee data new
      - name: sections
        identifier: _airbyte_raw_sections
        description: employee data new
      - name: sector_job_roles
        identifier: _airbyte_raw_sectorjobroles
        description: employee data new
      - name: sectors
        identifier: _airbyte_raw_sectors
        description: employee data new
      - name: student_class_details
        identifier: _airbyte_raw_studentclassdetails
        description: employee data new
      - name: student_classes
        identifier: _airbyte_raw_studentclasses
        description: employee data new
      - name: student_class_mapping
        identifier: _airbyte_raw_studentclassmapping
        description: employee data new
      - name: students_for_exit_form
        identifier: _airbyte_raw_studentsforexitform
        description: employee data new
      - name: vc_school_sectors
        identifier: _airbyte_raw_vcschoolsectors
        description: employee data new
      - name: vocational_training_providers
        identifier: _airbyte_raw_vocationaltrainingproviders
        description: employee data new
      - name: vt_class_students
        identifier: _airbyte_raw_vtclassstudents
        description: employee data new
      - name: vtp_sector_job_roles
        identifier: _airbyte_raw_vtpsectorjobroles
        description: employee data new
      - name: vtp_sectors
        identifier: _airbyte_raw_vtpsectors
        description: employee data new
      - name: vt_school_classes
        identifier: _airbyte_raw_vtschoolclasses
        description: employee data new
      - name: vt_school_sector_job_roles
        identifier: _airbyte_raw_vtschoolsectorjobroles
        description: employee data new
      - name: vt_school_sectors
        identifier: _airbyte_raw_vtschoolsectors
        description: employee data new
